<a href="https://colab.research.google.com/github/geonextgis/Mastering-Machine-Learning-and-GEE-for-Earth-Science/blob/main/01_Data_Gathering/01_Understanding_the_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Understanding the Data**
Understanding the data is a critical step in the data science process. It involves gaining insights into the structure, content, quality, and characteristics of the data you're working with. Properly understanding the data sets the foundation for making informed decisions, building accurate models, and deriving meaningful insights.

## **Import Required Libraries**

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
import pandas as pd

## **Read the Data**

In [6]:
df = pd.read_csv(r"/content/drive/MyDrive/Colab Notebooks/GitHub Repo/Mastering-Machine-Learning-and-GEE-for-Earth-Science/Datasets/Global YouTube Statistics.csv", encoding="latin")

## **How Big is the Data?**

In [7]:
df.shape

(995, 28)

## **How does the Data look like?**

In [8]:
# Print first 5 rows of the dataframe
df.head()

,rank,Youtuber,subscribers,video views,category,Title,uploads,Country,Abbreviation,channel_type,...,subscribers_for_last_30_days,created_year,created_month,created_date,Gross tertiary education enrollment (%),Population,Unemployment rate,Urban_population,Latitude,Longitude
0,1,T-Series,245000000,2.280000e+11,Music,T-Series,20082,India,IN,Music,...,2000000.0,2006.0,Mar,13.0,28.1,1.366418e+09,5.36,471031528.0,20.593684,78.962880
1,2,YouTube Movies,170000000,0.000000e+00,Film & Animation,youtubemovies,1,United States,US,Games,...,NaN,2006.0,Mar,5.0,88.2,3.282395e+08,14.70,270663028.0,37.090240,-95.712891
2,3,MrBeast,166000000,2.836884e+10,Entertainment,MrBeast,741,United States,US,Entertainment,...,8000000.0,2012.0,Feb,20.0,88.2,3.282395e+08,14.70,270663028.0,37.090240,-95.712891
3,4,Cocomelon - Nursery Rhymes,162000000,1.640000e+11,Education,Cocomelon - Nursery Rhymes,966,United States,US,Education,...,1000000.0,2006.0,Sep,1.0,88.2,3.282395e+08,14.70,270663028.0,37.090240,-95.712891
4,5,SET India,159000000,1.480000e+11,Shows,SET India,116536,India,IN,Entertainment,...,1000000.0,2006.0,Sep,20.0,28.1,1.366418e+09,5.36,471031528.0,20.593684,78.962880

In [9]:
# Randomly choose 5 rows and print it
df.sample(5)

,rank,Youtuber,subscribers,video views,category,Title,uploads,Country,Abbreviation,channel_type,...,subscribers_for_last_30_days,created_year,created_month,created_date,Gross tertiary education enrollment (%),Population,Unemployment rate,Urban_population,Latitude,Longitude
560,561,Jordan Matter,16600000,5.819509e+09,Entertainment,Jordan Matter,413,United States,US,Entertainment,...,300000.0,2006.0,Dec,21.0,88.2,3.282395e+08,14.70,270663028.0,37.090240,-95.712891
831,832,Acenix,13600000,2.122062e+09,Gaming,Acenix,368,Spain,ES,Games,...,200000.0,2014.0,Jan,2.0,88.9,4.707678e+07,13.96,37927409.0,40.463667,-3.749220
844,845,Sanjoy Das Official,13500000,3.912334e+09,Entertainment,Sanjoy Das Official,1793,India,IN,Games,...,400000.0,2015.0,Apr,29.0,28.1,1.366418e+09,5.36,471031528.0,20.593684,78.962880
275,276,That Little Puff,23700000,2.028969e+10,Pets & Animals,That Little Puff,769,United States,US,Animals,...,1100000.0,2020.0,Aug,29.0,88.2,3.282395e+08,14.70,270663028.0,37.090240,-95.712891
710,711,Major Lazer Official,14800000,9.383431e+09,Music,MajorLazerOfficial,0,NaN,NaN,NaN,...,NaN,2013.0,Jun,14.0,NaN,NaN,NaN,NaN,NaN,NaN

## **What are the Data Types of the Columns?**

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 995 entries, 0 to 994
Data columns (total 28 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   rank                                     995 non-null    int64
 1   Youtuber                                 995 non-null    object
 2   subscribers                              995 non-null    int64
 3   video views                              995 non-null    float64
 4   category                                 949 non-null    object
 5   Title                                    995 non-null    object
 6   uploads                                  995 non-null    int64
 7   Country                                  873 non-null    object
 8   Abbreviation                             873 non-null    object
 9   channel_type                             965 non-null    object
 10  video_views_rank                         994 non-null    float64
 11  country_rank                             879 non-null    float64
 12  channel_type_rank                        962 non-null    float64
 13  video_views_for_the_last_30_days         939 non-null    float64
 14  lowest_monthly_earnings                  995 non-null    float64
 15  highest_monthly_earnings                 995 non-null    float64
 16  lowest_yearly_earnings                   995 non-null    float64
 17  highest_yearly_earnings                  995 non-null    float64
 18  subscribers_for_last_30_days             658 non-null    float64
 19  created_year                             990 non-null    float64
 20  created_month                            990 non-null    object
 21  created_date                             990 non-null    float64
 22  Gross tertiary education enrollment (%)  872 non-null    float64
 23  Population                               872 non-null    float64
 24  Unemployment rate                        872 non-null    float64
 25  Urban_population                         872 non-null    float64
 26  Latitude                                 872 non-null    float64
 27  Longitude                                872 non-null    float64
dtypes: float64(18), int64(3), object(7)
memory usage: 217.8+ KB

## **Are there any Missing Values?**

In [11]:
# Checking the number of missing values for each column
df.isnull().sum()

rank                                         0
Youtuber                                     0
subscribers                                  0
video views                                  0
category                                    46
Title                                        0
uploads                                      0
Country                                    122
Abbreviation                               122
channel_type                                30
video_views_rank                             1
country_rank                               116
channel_type_rank                           33
video_views_for_the_last_30_days            56
lowest_monthly_earnings                      0
highest_monthly_earnings                     0
lowest_yearly_earnings                       0
highest_yearly_earnings                      0
subscribers_for_last_30_days               337
created_year                                 5
created_month                                5
created_date                                 5
Gross tertiary education enrollment (%)    123
Population                                 123
Unemployment rate                          123
Urban_population                           123
Latitude                                   123
Longitude                                  123
dtype: int64

## **How does the Data look Mathematically?**

In [12]:
df.describe()

,rank,subscribers,video views,uploads,video_views_rank,country_rank,channel_type_rank,video_views_for_the_last_30_days,lowest_monthly_earnings,highest_monthly_earnings,...,highest_yearly_earnings,subscribers_for_last_30_days,created_year,created_date,Gross tertiary education enrollment (%),Population,Unemployment rate,Urban_population,Latitude,Longitude
count,995.00000,9.950000e+02,9.950000e+02,995.000000,9.940000e+02,879.000000,962.000000,9.390000e+02,995.000000,9.950000e+02,...,9.950000e+02,6.580000e+02,990.000000,990.000000,872.000000,8.720000e+02,872.000000,8.720000e+02,872.000000,872.000000
mean,498.00000,2.298241e+07,1.103954e+10,9187.125628,5.542489e+05,386.053470,745.719335,1.756103e+08,36886.148281,5.898078e+05,...,7.081814e+06,3.490791e+05,2012.630303,15.746465,63.627752,4.303873e+08,9.279278,2.242150e+08,26.632783,-14.128146
std,287.37606,1.752611e+07,1.411084e+10,34151.352254,1.362782e+06,1232.244746,1944.386561,4.163782e+08,71858.724092,1.148622e+06,...,1.379704e+07,6.143554e+05,4.512503,8.777520,26.106893,4.727947e+08,4.888354,1.546874e+08,20.560533,84.760809
min,1.00000,1.230000e+07,0.000000e+00,0.000000,1.000000e+00,1.000000,1.000000,1.000000e+00,0.000000,0.000000e+00,...,0.000000e+00,1.000000e+00,1970.000000,1.000000,7.600000,2.025060e+05,0.750000,3.558800e+04,-38.416097,-172.104629
25%,249.50000,1.450000e+07,4.288145e+09,194.500000,3.230000e+02,11.000000,27.000000,2.013750e+07,2700.000000,4.350000e+04,...,5.217500e+05,1.000000e+05,2009.000000,8.000000,36.300000,8.335541e+07,5.270000,5.590832e+07,20.593684,-95.712891
50%,498.00000,1.770000e+07,7.760820e+09,729.000000,9.155000e+02,51.000000,65.500000,6.408500e+07,13300.000000,2.127000e+05,...,2.600000e+06,2.000000e+05,2013.000000,16.000000,68.000000,3.282395e+08,9.365000,2.706630e+08,37.090240,-51.925280
75%,746.50000,2.460000e+07,1.355470e+10,2667.500000,3.584500e+03,123.000000,139.750000,1.688265e+08,37900.000000,6.068000e+05,...,7.300000e+06,4.000000e+05,2016.000000,23.000000,88.200000,3.282395e+08,14.700000,2.706630e+08,37.090240,78.962880
max,995.00000,2.450000e+08,2.280000e+11,301308.000000,4.057944e+06,7741.000000,7741.000000,6.589000e+09,850900.000000,1.360000e+07,...,1.634000e+08,8.000000e+06,2022.000000,31.000000,113.100000,1.397715e+09,14.720000,8.429340e+08,61.924110,138.252924

## **Are there any Duplicate Rows?**

In [13]:
df.duplicated().sum()

0

## **How is the Correlation between Columns?**

In [14]:
# Extract the correlation between all the variables
df.corr()

,rank,subscribers,video views,uploads,video_views_rank,country_rank,channel_type_rank,video_views_for_the_last_30_days,lowest_monthly_earnings,highest_monthly_earnings,...,highest_yearly_earnings,subscribers_for_last_30_days,created_year,created_date,Gross tertiary education enrollment (%),Population,Unemployment rate,Urban_population,Latitude,Longitude
rank,1.000000,-0.640608,-0.453363,-0.051036,-0.059455,0.016776,-0.029554,-0.186339,-0.248394,-0.248050,...,-0.248392,-0.188571,0.106025,-0.006256,-0.037491,-0.025475,-0.014860,-0.038807,0.000036,0.019003
subscribers,-0.640608,1.000000,0.750958,0.077136,0.057202,0.032683,0.027393,0.278846,0.388941,0.388579,...,0.388935,0.309527,-0.141827,-0.011836,-0.006804,0.082219,-0.008251,0.083521,0.019450,0.022443
video views,-0.453363,0.750958,1.000000,0.165928,-0.061807,-0.068277,-0.050194,0.361856,0.552096,0.551455,...,0.552091,0.187384,-0.127068,-0.038180,-0.015232,0.080214,-0.000729,0.076649,0.037334,0.031268
uploads,-0.051036,0.077136,0.165928,1.000000,-0.108988,-0.078394,-0.098450,0.101521,0.166922,0.167283,...,0.166904,0.008933,-0.154904,0.034900,-0.218396,0.143122,-0.188101,0.072807,-0.067868,0.233169
video_views_rank,-0.059455,0.057202,-0.061807,-0.108988,1.000000,0.877504,0.949936,-0.067193,-0.208863,-0.208935,...,-0.208851,-0.167295,0.006671,0.031231,0.046934,-0.103178,-0.029276,-0.122747,0.015932,-0.016492
country_rank,0.016776,0.032683,-0.068277,-0.078394,0.877504,1.000000,0.898442,-0.098737,-0.148947,-0.148960,...,-0.148946,-0.126175,-0.037807,-0.012699,0.103290,-0.053181,0.066697,-0.024578,0.048323,-0.072476
channel_type_rank,-0.029554,0.027393,-0.050194,-0.098450,0.949936,0.898442,1.000000,-0.129051,-0.187908,-0.187970,...,-0.187896,-0.154021,-0.014002,0.038299,0.062484,-0.116254,0.003697,-0.123852,0.010195,-0.055144
video_views_for_the_last_30_days,-0.186339,0.278846,0.361856,0.101521,-0.067193,-0.098737,-0.129051,1.000000,0.680330,0.680289,...,0.680330,0.451523,0.053123,-0.013670,-0.035610,0.053859,-0.002323,0.051126,-0.026864,0.049033
lowest_monthly_earnings,-0.248394,0.388941,0.552096,0.166922,-0.208863,-0.148947,-0.187908,0.680330,1.000000,0.999955,...,0.999998,0.679360,0.072316,-0.040269,-0.062190,0.104812,-0.042874,0.081206,0.006583,0.100379
highest_monthly_earnings,-0.248050,0.388579,0.551455,0.167283,-0.208935,-0.148960,-0.187970,0.680289,0.999955,1.000000,...,0.999953,0.679699,0.072289,-0.039959,-0.061973,0.104785,-0.042627,0.081226,0.006873,0.100299
lowest_yearly_earnings,-0.248593,0.389072,0.552776,0.167745,-0.208950,-0.149020,-0.187993,0.680278,0.999942,0.999884,...,0.999941,0.678394,0.071911,-0.040047,-0.062553,0.104693,-0.043045,0.081025,0.006691,0.100485
highest_yearly_earnings,-0.248392,0.388935,0.552091,0.166904,-0.208851,-0.148946,-0.187896,0.680330,0.999998,0.999953,...,1.000000,0.679380,0.072263,-0.040250,-0.062163,0.104783,-0.042860,0.081165,0.006532,0.100376
subscribers_for_last_30_days,-0.188571,0.309527,0.187384,0.008933,-0.167295,-0.126175,-0.154021,0.451523,0.679360,0.679699,...,0.679380,1.000000,0.152117,0.006792,-0.020294,0.038737,-0.021130,0.030968,-0.011655,0.072032
created_year,0.106025,-0.141827,-0.127068,-0.154904,0.006671,-0.037807,-0.014002,0.053123,0.072316,0.072289,...,0.072263,0.152117,1.000000,0.018641,-0.162160,0.119630,-0.134943,0.074276,-0.111889,0.167206
created_date,-0.006256,-0.011836,-0.038180,0.034900,0.031231,-0.012699,0.038299,-0.013670,-0.040269,-0.039959,...,-0.040250,0.006792,0.018641,1.000000,-0.087068,0.024012,-0.033133,0.012260,0.020419,0.026401
Gross tertiary education enrollment (%),-0.037491,-0.006804,-0.015232,-0.218396,0.046934,0.103290,0.062484,-0.035610,-0.062190,-0.061973,...,-0.062163,-0.020294,-0.162160,-0.087068,1.000000,-0.573302,0.670979,-0.299787,0.338324,-0.599461
Population,-0.025475,0.082219,0.080214,0.143122,-0.103178,-0.053181,-0.116254,0.053859,0.104812,0.104785,...,0.104783,0.038737,0.119630,0.024012,-0.573302,1.000000,-0.217695,0.909440,-0.107974,0.409426
Unemployment rate,-0.014860,-0.008251,-0.000729,-0.188101,-0.029276,0.066697,0.003697,-0.002323,-0.042874,-0.042627,...,-0.042860,-0.021130,-0.134943,-0.033133,0.670979,-0.217695,1.000000,0.142211,0.140594,-0.763279
Urban_population,-0.038807,0.083521,0.076649,0.072807,-0.122747,-0.024578,-0.123852,0.051126,0.081206,0.081226,...,0.081165,0.030968,0.074276,0.012260,-0.299787,0.909440,0.142211,1.000000,-0.020815,0.088956
Latitude,0.000036,0.019450,0.037334,-0.067868,0.015932,0.048323,0.010195,-0.026864,0.006583,0.006873,...,0.006532,-0.011655,-0.111889,0.020419,0.338324,-0.107974,0.140594,-0.020815,1.000000,-0.200219
Longitude,0.019003,0.022443,0.031268,0.233169,-0.016492,-0.072476,-0.055144,0.049033,0.100379,0.100299,...,0.100376,0.072032,0.167206,0.026401,-0.599461,0.409426,-0.763279,0.088956,-0.200219,1.000000

In [15]:
# Extract the correlation between the 'subscribers' and other numerical columns
df.corr()["subscribers"]

rank                                      -0.640608
subscribers                                1.000000
video views                                0.750958
uploads                                    0.077136
video_views_rank                           0.057202
country_rank                               0.032683
channel_type_rank                          0.027393
video_views_for_the_last_30_days           0.278846
lowest_monthly_earnings                    0.388941
highest_monthly_earnings                   0.388579
lowest_yearly_earnings                     0.389072
highest_yearly_earnings                    0.388935
subscribers_for_last_30_days               0.309527
created_year                              -0.141827
created_date                              -0.011836
Gross tertiary education enrollment (%)   -0.006804
Population                                 0.082219
Unemployment rate                         -0.008251
Urban_population                           0.083521
Latitude                                   0.019450
Longitude                                  0.022443
Name: subscribers, dtype: float64